spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
