spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: seller_service
          uri: lb://seller-service
          predicates:
            - Path=/api/seller/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8090/realms/padmini-farms
        registration:
          keycloak:
            client-id: padmini-gateway
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/padmini-farms

# IMPORTANT: use service name "keycloak" (matches docker-compose service)
keycloak:
  server-url: http://keycloak:8090
  realm: padmini-farms
  admin:
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
